In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

visa_df=pd.read_csv('Visadataset.csv')

cat=visa_df.select_dtypes(include='object').columns
num=visa_df.select_dtypes(exclude='object').columns

In [3]:
dict1={'Name': ['Ramesh','Suresh', 'Sathish',np.nan],
'Age': [30,33,np.nan,36],
      'City': [np.nan,'Hyd', 'Hyd', 'Blr']}

In [4]:
data=pd.DataFrame(dict1)
data

Name   Age City
0   Ramesh  30.0  NaN
1   Suresh  33.0  Hyd
2  Sathish   NaN  Hyd
3      NaN  36.0  Blr

In [5]:
data.to_csv('data1.csv',index=False)

**isnull**

In [6]:
data.isnull()

Name    Age   City
0  False  False   True
1  False  False  False
2  False   True  False
3   True  False  False

In [7]:
data.isnull().sum()

Name    1
Age     1
City    1
dtype: int64

**dropna**
   - drop the null values data based on rows and columns

In [8]:
# Iwant to extract the data without Null values 
data.dropna()

Name   Age City
1  Suresh  33.0  Hyd

In [9]:
data

Name   Age City
0   Ramesh  30.0  NaN
1   Suresh  33.0  Hyd
2  Sathish   NaN  Hyd
3      NaN  36.0  Blr

In [10]:
data.dropna(axis=1)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3]

In [11]:
dict1={'Name': ['Ramesh','Suresh', 'Sathish',np.nan],
'Age': [30,33,np.nan,36],
      'City': [np.nan,'Hyd', 'Hyd', 'Blr'],
      'Company':['Google','Microsoft','Apple','Meta']}
data1=pd.DataFrame(dict1)
data1

Name   Age City    Company
0   Ramesh  30.0  NaN     Google
1   Suresh  33.0  Hyd  Microsoft
2  Sathish   NaN  Hyd      Apple
3      NaN  36.0  Blr       Meta

In [12]:
data1.dropna(axis=1)

Company
0     Google
1  Microsoft
2      Apple
3       Meta

**Fillna**

In [11]:
data1.fillna()

ValueError: Must specify a fill 'value' or 'method'.

In [12]:
data1.fillna(30)

Name   Age City    Company
0   Ramesh  30.0   30     Google
1   Suresh  33.0  Hyd  Microsoft
2  Sathish  30.0  Hyd      Apple
3       30  36.0  Blr       Meta

In [13]:
# first select the column
# then apply fill na 
data1['Name'].fillna('Manish')

0     Ramesh
1     Suresh
2    Sathish
3     Manish
Name: Name, dtype: object

**Draw back: Filling with Random value is not a good approach**

   - To avoid the we have some methods 

       - backfill

       - bfill

       - ffill

       - pad

**pad**

In [14]:
import warnings
warnings

<module 'warnings' from 'C:\\Program Files\\Python313\\Lib\\warnings.py'>

In [14]:
data1.fillna(method='pad')

C:\Users\HP\AppData\Local\Temp\ipykernel_11336\116358274.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data1.fillna(method='pad')


Name   Age City    Company
0   Ramesh  30.0  NaN     Google
1   Suresh  33.0  Hyd  Microsoft
2  Sathish  33.0  Hyd      Apple
3  Sathish  36.0  Blr       Meta

In [ ]:
idea-1: filling with random value - df.fillname(<random value>)
idea-2: filling with rv base on column=df[<col>].fillname
idea-3: filling with some pattern using a ethod: df.fillna
idea-4: filling with m-m-m based on volumn=df[<col>].fillna
idea-5: filling with avg value only selected neighbours

In [15]:
import warnings
warnings.filterwarnings('ignore')
data1.fillna(method='pad')


Name   Age City    Company
0   Ramesh  30.0  NaN     Google
1   Suresh  33.0  Hyd  Microsoft
2  Sathish  33.0  Hyd      Apple
3  Sathish  36.0  Blr       Meta

In [15]:
import warnings
warnings.filterwarnings('ignore')
data1.fillna(method='pad', axis=1)

Name      Age  City    Company
0   Ramesh     30.0  30.0     Google
1   Suresh     33.0   Hyd  Microsoft
2  Sathish  Sathish   Hyd      Apple
3      NaN     36.0   Blr       Meta

In [16]:
data1

Name   Age City    Company
0   Ramesh  30.0  NaN     Google
1   Suresh  33.0  Hyd  Microsoft
2  Sathish   NaN  Hyd      Apple
3      NaN  36.0  Blr       Meta

In [16]:
import warnings
warnings.filterwarnings('ignore')
data1.fillna(method='pad',axis=1)

Name      Age  City    Company
0   Ramesh     30.0  30.0     Google
1   Suresh     33.0   Hyd  Microsoft
2  Sathish  Sathish   Hyd      Apple
3      NaN     36.0   Blr       Meta

In [17]:
import warnings
warnings.filterwarnings('ignore')
data1.fillna(method='backfill')

Name   Age City    Company
0   Ramesh  30.0  Hyd     Google
1   Suresh  33.0  Hyd  Microsoft
2  Sathish  36.0  Hyd      Apple
3      NaN  36.0  Blr       Meta

In [18]:
import warnings
warnings.filterwarnings('ignore')
data1.fillna(method='bfill')

Name   Age City    Company
0   Ramesh  30.0  Hyd     Google
1   Suresh  33.0  Hyd  Microsoft
2  Sathish  36.0  Hyd      Apple
3      NaN  36.0  Blr       Meta

In [19]:
import warnings
warnings.filterwarnings('ignore')
data1.fillna(method='ffill')

Name   Age City    Company
0   Ramesh  30.0  NaN     Google
1   Suresh  33.0  Hyd  Microsoft
2  Sathish  33.0  Hyd      Apple
3  Sathish  36.0  Blr       Meta

In [20]:
import warnings
warnings.filterwarnings('ignore')
data1.fillna(method='pad')

Name   Age City    Company
0   Ramesh  30.0  NaN     Google
1   Suresh  33.0  Hyd  Microsoft
2  Sathish  33.0  Hyd      Apple
3  Sathish  36.0  Blr       Meta

**Mean-Median_mode**

In [22]:
# select the column
# get the mean
# apply fill na

age_mean=data1['Age'].mean()
print('age_mean:',age_mean)
data1['Age'].fillna(age_mean)

age_mean: 33.0


0    30.0
1    33.0
2    33.0
3    36.0
Name: Age, dtype: float64

In [18]:
city_mode=data1['City'].mode()
data1['City'].fillna(city_mode)

0    Hyd
1    Hyd
2    Hyd
3    Blr
Name: City, dtype: object

In [23]:
age_mean # fixed value

np.float64(33.0)

In [19]:
city_mode

0    Hyd
Name: City, dtype: object

In [20]:
# static value 
city_mode.values[0]

'Hyd'

- in future sometimes if we direct impute mode value we will get error

- mode is coming as series

- mean is coming as fixed value

- so first convert series to fixed value then apply it 

In [21]:
city_mode.values[0]

'Hyd'

In [22]:
city_mode=data1['City'].mode()
data1['City'].fillna(city_mode.values[0])

0    Hyd
1    Hyd
2    Hyd
3    Blr
Name: City, dtype: object

**impute class**

In [25]:
from sklearn import impute

In [26]:
dir(impute)

['KNNImputer',
 'MissingIndicator',
 'SimpleImputer',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_base',
 '_knn',
 'typing']

**KNNImputer**
- K- Nearest Neighbours

- where k = hyper parameter which means the user can change

- Idea: Instead of taking all the sample average

   - First fix the neighbours number i.e. k

   - Then fix the neighbours using distance metric

   - Then take the average of those amples to fill the missing value

**impute**

In [28]:
import numpy as np
from sklearn.impute import KNNImputer
X = [[1,2, np.nan],[3,np.nan,3],[np.nan,60,5],[8,8,7]]
pd.DataFrame(X)

0     1    2
0  1.0   2.0  NaN
1  3.0   NaN  3.0
2  NaN  60.0  5.0
3  8.0   8.0  7.0

In [27]:
import numpy as np
from sklearn.impute import KNNImputer
X = [[1,2, np.nan],[3,np.nan,3],[np.nan,60,5],[8,8,7]]
imputer=KNNImputer(n_neighbors=2)
imputer.fit_transform(X)

array([[ 1. ,  2. ,  5. ],
       [ 3. , 31. ,  3. ],
       [ 5.5, 60. ,  5. ],
       [ 8. ,  8. ,  7. ]])

In [30]:
import numpy as np
from sklearn.impute import KNNImputer
X = [[1,2, np.nan],[3,np.nan,3],[np.nan,60,5],[8,8,7]]
imputer=KNNImputer(n_neighbors=2, weights='distance')
imputer.fit_transform(X)

array([[ 1.        ,  2.        ,  3.93905505],
       [ 3.        , 31.        ,  3.        ],
       [ 3.25775362, 60.        ,  5.        ],
       [ 8.        ,  8.        ,  7.        ]])

In [ ]:
when we see what? Mean, Median, Mode?
Median

1. Green line separates very well 
2. the separation from two classes its doing very well
3. Calculate the border points of each class
4. we will calculate a line
5. that line should maintain a maximum distance from those point

Distance between line to point

KNN K nearest neighbours 
k= is a numbers
how many neighbours need to choose
how many nearest sourrounding data points

In [32]:
import numpy as np
from sklearn.impute import KNNImputer
X = [[1,2, np.nan],[3,np.nan,3],[np.nan,60,5],[8,8,7]]
imputer=KNNImputer(n_neighbors=2, weights='uniform')
imputer.fit_transform(X)

array([[ 1. ,  2. ,  5. ],
       [ 3. , 31. ,  3. ],
       [ 5.5, 60. ,  5. ],
       [ 8. ,  8. ,  7. ]])

In [31]:
import numpy as np
from sklearn.impute import KNNImputer
X = [[1,2, np.nan],[3,np.nan,3],[np.nan,60,5],[8,8,7]]
imputer=KNNImputer(n_neighbors=2, weights='distance')
imputer.fit_transform(X)

array([[ 1.        ,  2.        ,  3.93905505],
       [ 3.        , 31.        ,  3.        ],
       [ 3.25775362, 60.        ,  5.        ],
       [ 8.        ,  8.        ,  7.        ]])

In [ ]:
idea-1: filling with random value=df.fillname(<random value>)
idea-2: filling with rv based on column=df[<col>].fillname(<rv>)
idea-3: filling with some pattern using a method: df.fillna(<method>)
idea-4: filling with m-m-m based on column = df[<col>].fillname(<m> or <m> or <m>)
idea-5: filling with avg value only selected neighbours
idea-6: filling with a value based on correlation with another columns

In [28]:
import numpy as np
from sklearn.impute import KNNImputer
X = [[1,2, np.nan],[3,np.nan,3],[np.nan,60,5],[8,8,7]]
imputer=KNNImputer(n_neighbors=2,weights='uniform')
imputer.fit_transform(X)

array([[ 1. ,  2. ,  5. ],
       [ 3. , 31. ,  3. ],
       [ 5.5, 60. ,  5. ],
       [ 8. ,  8. ,  7. ]])

In [32]:
import numpy as np
from sklearn.impute import KNNImputer
X = [[1,2, np.nan],[3,np.nan,3],[np.nan,60,5],[8,8,7]]
imputer=KNNImputer(n_neighbors=2,weights='distance')
imputer.fit_transform(X)

array([[ 1.        ,  2.        ,  3.93905505],
       [ 3.        , 31.        ,  3.        ],
       [ 3.25775362, 60.        ,  5.        ],
       [ 8.        ,  8.        ,  7.        ]])

In [ ]:
KNN k nearest neighbours
k=numbers
how many 